version: '3.4'

x-common-config: &common-env
  TZ: Asia/Taipei

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    hostname: sqlserver
    environment:
      <<: *common-env
      SA_PASSWORD: Pass@word
      ACCEPT_EULA: 'Y'
    ports:
      - "1433:1433"
    # volumes:
    #   - type: volume
    #     source: sqlserver-volume-data
    #     target: /var/opt/mssql/data 
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "Pass@word" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 10s
      retries: 50           
    networks:
      - backend
  kong:
    environment:
      - KONG_SSL_CERT=/ssl/dev.crt
      - KONG_SSL_CERT_KEY=/ssl/dev.key

  domainstorm.metadataapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DomainStorm_SqlDbOptions__ConnectionString: Server=sqlserver;Database=MetadataApiEventDb;User Id=sa;Password=Pass@word;  
    depends_on:   
      sqlserver:
        condition: service_healthy  
  domainstorm.multimediaapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  domainstorm.jwtauthapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DomainStorm_SqlDbOptions__ConnectionString: Server=sqlserver;Database=JwtAuthEventDb;User Id=sa;Password=Pass@word;
    volumes:
      - "./appsettings/jwtauthapi/appsettings.TWC.json:/app/appsettings.Development.json"       
    depends_on:   
      sqlserver:
        condition: service_healthy  
  domainstorm.jwtauthapi.openidprovider:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DomainStorm_SqlServerOptions__ConnectionString: Server=sqlserver;Database=OpenIddict;User Id=sa;Password=Pass@word;
      DomainStorm_Login__Use: LDAP
    volumes:
      - "./appsettings/openidprovider/appsettings.TWC.json:/app/appsettings.Development.json"   
    depends_on:
      sqlserver:
          condition: service_healthy  
  domainstorm.project.twc.web:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/dev.pfx
      DomainStorm_SqlDbOptions__ConnectionString: Server=sqlserver;Database=TWCWeb;User Id=sa;Password=Pass@word;
      DomainStorm_PostInteropExe: "false"
      DomainStorm_TwcReportPathBase: https://localhost:8443/twcreport
    depends_on:   
      sqlserver:
        condition: service_healthy            
  domainstorm.resourceapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DomainStorm_SqlDbOptions__ConnectionString: Server=sqlserver;Database=ResourceEventDb;User Id=sa;Password=Pass@word;
    volumes:
      - "./appsettings/resourceapi/appsettings.TWC.json:/app/appsettings.Development.json"  
    depends_on:   
      sqlserver:
        condition: service_healthy        
  domainstorm.servicebus:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  domainstorm.project.twc.report:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DomainStorm_SqlDbOptions__ConnectionString: Server=sqlserver;Database=TWCWeb;User Id=sa;Password=Pass@word;
    depends_on:   
      sqlserver:
        condition: service_healthy        

# volumes:
#   sqlserver-volume-data:      
