version: '3.4'

x-common-config: &common-env
  TZ: Asia/Taipei

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    hostname: sqlserver
    user: root
    environment:
      <<: *common-env
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Pass@word'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer' 
      MSSQL_TCP_PORT: 1433 
    ports:
      - "1433:1433"
    volumes:
        - ./mssql/data:/var/opt/mssql/data
        - ./mssql/log:/var/opt/mssql/log
        - ./mssql/secrets:/var/opt/mssql/secrets
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PPass@word", "-Q", "select 1"]
      interval: 10s
      timeout: 10s
      retries: 50           
    networks:
      - backend
  kong:
    environment:
      - KONG_SSL_CERT=/ssl/dev.crt
      - KONG_SSL_CERT_KEY=/ssl/dev.key

  domainstorm.metadataapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DomainStorm_SqlDbOptions__ConnectionString: Server=sqlserver;Database=MetadataApiEventDb;User Id=sa;Password=Pass@word;  
    depends_on:   
      sqlserver:
        condition: service_healthy  
  domainstorm.multimediaapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  domainstorm.jwtauthapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DomainStorm_SqlDbOptions__ConnectionString: Server=sqlserver;Database=JwtAuthEventDb;User Id=sa;Password=Pass@word;
    volumes:
      - "./appsettings/jwtauthapi/appsettings.TWC.json:/app/appsettings.Development.json"       
    depends_on:   
      sqlserver:
        condition: service_healthy  
  domainstorm.jwtauthapi.openidprovider:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DomainStorm_SqlServerOptions__ConnectionString: Server=sqlserver;Database=OpenIddict;User Id=sa;Password=Pass@word;
      DomainStorm_Login__Use: LDAP
    volumes:
      - "./appsettings/openidprovider/appsettings.TWC.json:/app/appsettings.Development.json"   
    depends_on:
      sqlserver:
          condition: service_healthy  
  domainstorm.project.twc.web:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/dev.pfx
      DomainStorm_SqlDbOptions__ConnectionString: Server=sqlserver;Database=TWCWeb;User Id=sa;Password=Pass@word;
      DomainStorm_PostInteropExe: "false"
      DomainStorm_TwcReportPathBase: https://localhost:8443/twcreport
    depends_on:   
      sqlserver:
        condition: service_healthy            
  domainstorm.resourceapi:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DomainStorm_SqlDbOptions__ConnectionString: Server=sqlserver;Database=ResourceEventDb;User Id=sa;Password=Pass@word;
    volumes:
      - "./appsettings/resourceapi/appsettings.TWC.json:/app/appsettings.Development.json"  
    depends_on:   
      sqlserver:
        condition: service_healthy        
  domainstorm.servicebus:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
  domainstorm.project.twc.report:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DomainStorm_SqlDbOptions__ConnectionString: Server=sqlserver;Database=TWCWeb;User Id=sa;Password=Pass@word;
    depends_on:   
      sqlserver:
        condition: service_healthy        

# volumes:
#   sqlserver-volume-data:      
