name: E2E Tests

on:
  push:
    branches:
      - '**'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Get IP address
        run: |
          IP_ADDRESS=$(ifconfig eth0 | grep 'inet ' | awk '{print $2}')
          echo "IP_ADDRESS=$IP_ADDRESS" >> $GITHUB_ENV

      - name: Set environment variables
        run: |
            echo "TestConfig__ApplyCaseNo=12345678" >> $GITHUB_ENV
            echo "TestConfig__UserId=${{ secrets.TestConfig__UserId }}" >> $GITHUB_ENV
            echo "TestConfig__Password=${{ secrets.TestConfig__Password }}" >> $GITHUB_ENV            
            echo "TestConfig__BaseUrl=http://${{ env.IP_ADDRESS }}:8000" >> $GITHUB_ENV
            echo "TestConfig__TokenUrl=http://${{ env.IP_ADDRESS }}:8000/openid/connect/token" >> $GITHUB_ENV
            echo "Api_Gateway_EndPoint=https://${{ env.IP_ADDRESS }}:8443" >> $GITHUB_ENV
            echo "OpenIDConnectOptions_Authority=http://${{ env.IP_ADDRESS }}:8000/openid" >> $GITHUB_ENV
            echo "SignalR_EndPoint=http://${{ env.IP_ADDRESS }}:8000/hubUrl" >> $GITHUB_ENV

            ping -c 5 ${{ env.IP_ADDRESS }}
            
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip libgconf-2-4 libxss1 libappindicator1 libindicator7

          # Install Google Chrome
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable 
      - name: Print Chrome Version
        run: |
          CHROME_VERSION=$(google-chrome-stable --version)
          echo "Installed Chrome Version: $CHROME_VERSION"  
            
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x            
          
      - name: Start containers
        run: pwsh -File deploy/deploy-dev.ps1           
      - name: Restore dependencies
        run: dotnet restore DomainStorm.Project.TWC.Tests.sln
      - name: Build
        run: dotnet build DomainStorm.Project.TWC.Tests.sln --no-restore
      - name: Test
        run: dotnet test DomainStorm.Project.TWC.Tests.sln --no-build --verbosity normal
