name: E2E Tests

on:
  push:
    branches:
      - '**'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "HOST_NAME=$HOSTNAME" >> $GITHUB_ENV
          echo "TestConfig_UserId=admin" >> $GITHUB_ENV
          echo "TestConfig_Password=adminadmin" >> $GITHUB_ENV  
          echo "TestConfig_BaseUrl=http://$HOST_NAME:8000" >> $GITHUB_ENV
          echo "TestConfig_TokenUrl=http://$HOST_NAME:8000/openid/connect/token" >> $GITHUB_ENV
   
          ping -c 5 $HOSTNAME
          
      - name: Start containers
        run: pwsh -File deploy/deploy-dev.ps1    
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
                    
          
      - name: Restore dependencies
        run: dotnet restore DomainStorm.Project.TWC.Tests.sln
      - name: Build
        run: dotnet build DomainStorm.Project.TWC.Tests.sln --no-restore
      - name: Test
        run: dotnet test DomainStorm.Project.TWC.Tests.sln --no-build --verbosity normal
